<?php
/**
 * Implements hook_node_presave().
 */
function dpipackagegenerator_node_presave($node) {

  // see: http://www.wunderkraut.com/blog/generating-realistic-test-content/2011-03-07
  if ($node->type == 'package' && isset($node->devel_generate)) {

    /*
    $images = field_get_items('node', $node, 'field_recipe_image');

    foreach ($images as $delta => $image) {
      // Pick one sample image randomly.
      $source = drupal_get_path('module', 'mymodule') . '/images/food' . rand(0, 9) . '.jpg';

      // Load the reference to the original from the database.
      $file = file_load($image['fid']);

      // Overwrite the original image with a copy of our sample image.
      $destination = $file->uri;
      $path = file_unmanaged_copy($source, $destination, FILE_EXISTS_REPLACE);
    }
    */



    //Enlever le use emabargo dans 95 pourcent des cas.




    //Ajouter entre 1 et 4 destinations.


    //Ajouter une linklist dans 10% des cas


    //AJouter entre 1 et 6 embedded.


    //Ajouter un author

    //Ajouter 0 à 3 concepts


    //Ajouter 0 à 3 Freetags

    //Ajouter 0 à 1 locations

    //ajuter 0 à 3 entitieis

    //ajuter 0 à 2 Personnes



  }
}



function dpipackagegenerator_get_pool_of_destinations(){


  $tids= dpidestinations_api_get_all_sections_terms_flat_struct();

  $tid=array_rand ($tids);

  $target_blocks=dpidestinations_api_get_all_targetblocks_for_destination($tid->tid);

  $target_block=array_rand ($target_blocks);
  $targetblock_object=$target_blocks[$target_block];

  $target_object=dpidestinations_api_target_machinename_load($targetblock_object->target);

  $layouts=__dpidestinations_api_get_all_layouts_available_for_sectiontid_and_target($target_object->targetid,$targetblock_object->target);
  $layout=array_rand ($layouts);


  return array($tid,$target_block,$layout,'default');


}

function dpipackagegenerator_get_pool_of_taxonomies(){

}

function dpipackagegenerator_get_pool_of_linklists(){}

function dpipackagegenerator_get_pool_of_embeddedobjects(){}

function dpipackagegenerator_get_pool_of_taxonomy(){}

function dpipackagegenerator_get_pool_of_taxonomy(){}