<?php

module_load_include('inc', 'dpiexport','dpiexport.api');
module_load_include('inc', 'dpiexport','dpiexport.private');

/**
 * Implementation of hook_menu().
 */
function dpiexport_menu() {
  $items = array();

  $items[DPI_ADMIN_PATH.'/dpiexport'] = array(
    'title'            => t('DPI Export'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpiexport_page_admin_general_settings_form'),
    'access arguments' => array('export content'),
    'description'      => t('Configure and export packages.'),
    'file'             => 'includes/dpiexport.pages.admin.inc',
  );

  $items[DPI_ADMIN_PATH.'/dpiexport/settings'] = array(
    'title'            => t('General settings'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpiexport_page_admin_general_settings_form'),
    'access arguments' => array('export content'),
    'file'             => 'includes/dpiexport.pages.admin.inc',
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => 0,
  );

  $items[DPI_ADMIN_PATH.'/dpiexport/export'] = array(
    'title'            => t('Export'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpiexport_page_admin_export_form'),
    'access arguments' => array('export content'),
    'file'             => 'includes/dpiexport.pages.admin.inc',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 1,
  );

  $items['node/%node/dpixml'] = array(
    'title'            => t('Export package'),
    'page callback'    => 'dpiexport_page_export_package',
    'page arguments'   => array(1),
    'access arguments' => array('export content'),
    'description'      => t('Export packages to an XML output'),
    'file'             => 'includes/dpiexport.pages.export.inc',
    'type'             => MENU_CALLBACK,
  );

  $items['node/%node/dpixmlzip'] = array(
    'title'            => t('Export zipped package'),
    'page callback'    => 'dpiexport_page_export_zipped_package',
    'page arguments'   => array(1),
    'access arguments' => array('export content'),
    'description'      => t('Export packages to a zipped XML output'),
    'file'             => 'includes/dpiexport.pages.export.inc',
  );

  return $items;
}

/**
 * Implementation of hook_permission().
 */
function dpiexport_permission() {
  return array(
    'export content' =>  array(
      'title' => t('Export contents'),
    ),
  );
}

/**
 * Implementation of hook_menu_contextual_links_alter()
 */
function dpiexport_menu_contextual_links_alter(&$links, $router_item, $root_path) {
  // Add export links to all contextual links for nodes.
  if ($root_path == 'node/%') {
    $base_href = $router_item['href'];

    $links['node-export-xml'] = array(
      'title' => t('Export XML'),
      'href' => $base_href.'/dpixml',
      'localized_options' => array(), // Necessary to avoir fatal error
    );

    $links['node-export-zip'] = array(
      'title' => t('Export ZIP'),
      'href' => $base_href.'/dpixmlzip',
      'localized_options' => array(), // Necessary to avoir fatal error
    );
  }
}
