<?php 

module_load_include('inc', 'dpidashboard', 'dpidashboard.private');

function dpidashboard_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implementation of hook_views_api().
 */
function dpidashboard_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'dpidashboard') .'/views',
  );
}

