<?php 

module_load_include('inc', 'dpidashboard', 'dpidashboard.private');

function dpidashboard_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/content_types';
  }
  
}

function dpidashboard_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

function dpidashboard_default_page_manager_pages() {
  $pages = array();
  
  
	$page = new stdClass();
	$page->disabled = FALSE; /* Edit this to true to make a default page disabled initially */
	$page->api_version = 1;
	$page->name = 'dpi_dashboard';
	$page->task = 'page';
	$page->admin_title = 'DPI Dashboard';
	$page->admin_description = 'DPI Dashboard';
	$page->path = 'admin/dashboard';
	$page->access = array(
	  'plugins' => array(),
	  'logic' => 'and',
	);
	$page->menu = array();
	$page->arguments = array();
	$page->conf = array(
	  'admin_paths' => FALSE,
	);
	$page->default_handlers = array();
	$handler = new stdClass();
	$handler->disabled = FALSE; /* Edit this to true to make a default handler disabled initially */
	$handler->api_version = 1;
	$handler->name = 'page_dpi_dashboard_dpipanels_context';
	$handler->task = 'page';
	$handler->subtask = 'dpi_dashboard';
	$handler->handler = 'dpipanels_context';
	$handler->weight = 0;
	$handler->conf = array(
	  'no_blocks' => 0,
	  'pipeline' => 'standard',
	  'body_classes_to_remove' => '',
	  'body_classes_to_add' => '',
	  'css_id' => '',
	  'css' => '',
	  'contexts' => array(),
	  'relationships' => array(),
	  'title' => 'Dpi Panels',
	);
	$display = new panels_display();
	$display->layout = 'twocol_66_33';
	$display->layout_settings = array();
	$display->panel_settings = array(
	  'style_settings' => array(
		'default' => NULL,
		'left' => NULL,
		'right' => NULL,
		'tag1' => NULL,
		'tag2' => NULL,
		'tag3' => NULL,
		'bottom' => NULL,
	  ),
	);
	$display->cache = array();
	$display->title = '';
	$display->uuid = 'a3c84c1c-074f-4941-a589-d4494007f35b';
	$display->content = array();
	$display->panels = array();
	  $pane = new stdClass();
	  $pane->pid = 'new-4751e563-bdd3-484d-87f0-cbf2f32c6a14';
	  $pane->panel = 'left';
	  $pane->type = 'views_panes';
	  $pane->subtype = 'latest_published_by_someone-panel_pane_1';
	  $pane->shown = TRUE;
	  $pane->access = array();
	  $pane->configuration = array();
	  $pane->cache = array();
	  $pane->style = array();
	  $pane->css = array();
	  $pane->extras = array();
	  $pane->position = 0;
	  $pane->locks = array();
	  $pane->uuid = '4751e563-bdd3-484d-87f0-cbf2f32c6a14';
	  $display->content['new-4751e563-bdd3-484d-87f0-cbf2f32c6a14'] = $pane;
	  $display->panels['left'][0] = 'new-4751e563-bdd3-484d-87f0-cbf2f32c6a14';
	  $pane = new stdClass();
	  $pane->pid = 'new-b4a22c4f-9002-45d3-872a-72b115cb597d';
	  $pane->panel = 'left';
	  $pane->type = 'views';
	  $pane->subtype = 'latest_published_by_me';
	  $pane->shown = TRUE;
	  $pane->access = array();
	  $pane->configuration = array(
		'override_pager_settings' => 0,
		'use_pager' => 1,
		'nodes_per_page' => '10',
		'pager_id' => '0',
		'offset' => '0',
		'more_link' => 0,
		'feed_icons' => 0,
		'panel_args' => 0,
		'link_to_view' => 0,
		'args' => '',
		'url' => '',
		'display' => 'default',
		'override_title' => 0,
		'override_title_text' => '',
	  );
	  $pane->cache = array();
	  $pane->style = array();
	  $pane->css = array();
	  $pane->extras = array();
	  $pane->position = 1;
	  $pane->locks = array();
	  $pane->uuid = 'b4a22c4f-9002-45d3-872a-72b115cb597d';
	  $display->content['new-b4a22c4f-9002-45d3-872a-72b115cb597d'] = $pane;
	  $display->panels['left'][1] = 'new-b4a22c4f-9002-45d3-872a-72b115cb597d';
	  $pane = new stdClass();
	  $pane->pid = 'new-31db0d79-bfd2-4fa8-85c3-dd284fecbcfe';
	  $pane->panel = 'left';
	  $pane->type = 'views';
	  $pane->subtype = 'latest_edited_by_me';
	  $pane->shown = TRUE;
	  $pane->access = array();
	  $pane->configuration = array(
		'override_pager_settings' => 0,
		'use_pager' => 1,
		'nodes_per_page' => '2',
		'pager_id' => '0',
		'offset' => '0',
		'more_link' => 0,
		'feed_icons' => 0,
		'panel_args' => 0,
		'link_to_view' => 0,
		'args' => '',
		'url' => '',
		'display' => 'default',
		'override_title' => 0,
		'override_title_text' => '',
	  );
	  $pane->cache = array();
	  $pane->style = array();
	  $pane->css = array();
	  $pane->extras = array();
	  $pane->position = 2;
	  $pane->locks = array();
	  $pane->uuid = '31db0d79-bfd2-4fa8-85c3-dd284fecbcfe';
	  $display->content['new-31db0d79-bfd2-4fa8-85c3-dd284fecbcfe'] = $pane;
	  $display->panels['left'][2] = 'new-31db0d79-bfd2-4fa8-85c3-dd284fecbcfe';
	  $pane = new stdClass();
	  $pane->pid = 'new-bfc11d43-4c61-401d-98ff-a20d3cce8db0';
	  $pane->panel = 'right';
	  $pane->type = 'views';
	  $pane->subtype = 'latest_published';
	  $pane->shown = TRUE;
	  $pane->access = array();
	  $pane->configuration = array(
		'override_pager_settings' => 0,
		'use_pager' => 1,
		'nodes_per_page' => '10',
		'pager_id' => '0',
		'offset' => '0',
		'more_link' => 0,
		'feed_icons' => 0,
		'panel_args' => 0,
		'link_to_view' => 0,
		'args' => '',
		'url' => '',
		'display' => 'default',
		'override_title' => 0,
		'override_title_text' => '',
	  );
	  $pane->cache = array();
	  $pane->style = array();
	  $pane->css = array();
	  $pane->extras = array();
	  $pane->position = 0;
	  $pane->locks = array();
	  $pane->uuid = 'bfc11d43-4c61-401d-98ff-a20d3cce8db0';
	  $display->content['new-bfc11d43-4c61-401d-98ff-a20d3cce8db0'] = $pane;
	  $display->panels['right'][0] = 'new-bfc11d43-4c61-401d-98ff-a20d3cce8db0';
	  $pane = new stdClass();
	  $pane->pid = 'new-194f1fb1-fa7b-424a-8585-48c4aba82c35';
	  $pane->panel = 'right';
	  $pane->type = 'views';
	  $pane->subtype = 'latest_edited';
	  $pane->shown = TRUE;
	  $pane->access = array();
	  $pane->configuration = array(
		'override_pager_settings' => 0,
		'use_pager' => 1,
		'nodes_per_page' => '2',
		'pager_id' => '0',
		'offset' => '0',
		'more_link' => 0,
		'feed_icons' => 0,
		'panel_args' => 0,
		'link_to_view' => 0,
		'args' => '',
		'url' => '',
		'display' => 'default',
		'override_title' => 0,
		'override_title_text' => '',
	  );
	  $pane->cache = array();
	  $pane->style = array();
	  $pane->css = array();
	  $pane->extras = array();
	  $pane->position = 1;
	  $pane->locks = array();
	  $pane->uuid = '194f1fb1-fa7b-424a-8585-48c4aba82c35';
	  $display->content['new-194f1fb1-fa7b-424a-8585-48c4aba82c35'] = $pane;
	  $display->panels['right'][1] = 'new-194f1fb1-fa7b-424a-8585-48c4aba82c35';
	  $pane = new stdClass();
	  $pane->pid = 'new-3889d554-ff6e-49e1-948a-60e7da495286';
	  $pane->panel = 'right';
	  $pane->type = 'servertime';
	  $pane->subtype = 'servertime';
	  $pane->shown = TRUE;
	  $pane->access = array();
	  $pane->configuration = array();
	  $pane->cache = array();
	  $pane->style = array(
		'settings' => NULL,
	  );
	  $pane->css = array();
	  $pane->extras = array();
	  $pane->position = 2;
	  $pane->locks = array();
	  $pane->uuid = '3889d554-ff6e-49e1-948a-60e7da495286';
	  $display->content['new-3889d554-ff6e-49e1-948a-60e7da495286'] = $pane;
	  $display->panels['right'][2] = 'new-3889d554-ff6e-49e1-948a-60e7da495286';
	$display->hide_title = PANELS_TITLE_FIXED;
	$display->title_pane = 'new-3889d554-ff6e-49e1-948a-60e7da495286';
	$handler->conf['display'] = $display;
	$page->default_handlers[$handler->name] = $handler;

    $pages[$page->name] = $page;
   
  return $pages;
}

/**
 * Implementation of hook_views_api().
 */
function dpidashboard_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'dpidashboard') .'/views',
  );
}

