<?php


/**
 * Implements hook_node_info().
 *
 * We use hook_node_info() to define our node content type.
 */
function dpicontenttypes_node_info(){
  return array(
    'article_package'=>array(
      'name'=>t("Article Package"),
        
      'base'=>'article_package',
      'description'=>t('Article package from DPI'),
      'has_title'=>TRUE,  
      'locked' => FALSE,
                
    ),
    'gallery_package'=>array(
          'name'=>t("Gallery Package"),
      
          'base'=>'article_package',
          'description'=>t('Article package from DPI'),
          'has_title'=>TRUE,
          'locked' => FALSE,
      
      ),
      'poll_package'=>array(
          'name'=>t("Poll Package"),
      
          'base'=>'article_package',
          'description'=>t('Article package from DPI'),
          'has_title'=>TRUE,
          'locked' => FALSE,
      
      ),
  );
}




/**
 * Implement hook_form().
 *
 * Drupal needs for us to provide a form that lets the user
 * add content. This is the form that the user will see if
 * they go to node/add/node-example.
 *
 * You can get fancy with this form, or you can just punt
 * and return the default form that node_content will provide.
 */
function article_package_form($node, $form_state) {
  return node_content_form($node, $form_state);
}
function gallery_package_form($node, $form_state) {
  return node_content_form($node, $form_state);
}
function poll_package_form($node, $form_state) {
  return node_content_form($node, $form_state);
}


