  <?php

module_load_include('inc', 'dpidestinations','dpidestinations.api');
module_load_include('inc', 'dpidestinations','dpidestinations.private');
module_load_include('inc', 'dpidestinations','dpidestinations.helpers');
module_load_include('inc', 'dpidestinations','dpidestinations.field');
module_load_include('inc', 'dpidestinations','dpidestinations.entity');



/**
 * Implementation of hook_theme()
 */
function dpidestinations_theme() {
 
  $theme['dpidestinations_add_content_modal'] = array(
    'variables' => array('renderer' => NULL, 'groups' => array(), 'region' => NULL, 'category' => NULL,'group' => NULL, 'categories'=> array(), 'column_count' => 2),
    'path' => drupal_get_path('module', 'dpidestinations') . '/templates',
    'file' => 'theme.inc',
    'template' => 'dpidestinations-add-content-modal',
  );

    return $theme;
}

function dpidestinations_menu(){
  $items['destination/%destinationterm'] = array(
    'title callback' => 'destination_view',
    'title arguments' => array(1),
    'page callback' => 'destination_view',
    'page arguments' => array(1),
    'access arguments' => array('view targets'),
    'type' => MENU_CALLBACK,
  );
  $items['target/%target'] = array(
    'title callback' => 'target_page_title',
    'title arguments' => array(1),
    'page callback' => 'target_view',
    'page arguments' => array(1),
    'access arguments' => array('view targets'),
    'type' => MENU_CALLBACK,
  );
  $items['target/add'] = array(
    'title' => 'Add Target!',
    'page callback' => 'target_add',
    'access arguments' => array('create target'),
  );
  return $items;
}

function dpidestinations_permission(){
  return array(
    'administer targets' =>  array(
      'title' => t('Administer targets'),
      'restrict access' => TRUE,
    ),
    'view targetss' => array(
      'title' => t('View targets'),
    )
  );
}

function dpidestinations_panels_display_save($display){
  foreach($display->content as &$pane){
    if($pane->type =='targetblock'){
      $pane->configuration['override_title_text']='rr';
      $pane->configuration['override_title']=1;
    }
    
  }
}

function dpidestinations_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/ctools/content_types';
  }
  if ($module == 'page_manager' && $plugin == 'tasks') {
    return 'plugins/page_manager/tasks';
  }

  if ($module == 'page_manager' && $plugin == 'task_handlers') {
    return 'plugins/page_manager/task_handlers';
  }
  if ($module == 'panels' && $plugin == 'display_renderers') {
    return 'plugins/panels/display_renderers';
  }
  
}

function dpidestinations_entity_info_alter(&$entity_info){
  $entity_info["taxonomy_term"]["bundles"]["destinations"]["uri callback"]='dpidestinations_term_uri';
  
}

function dpidestinations_term_uri($term){
  return array(
      'path' => 'destination/' . $term->tid,
  );
}





function destinationterm_load($destination_id){
  return 1;
  return taxonomy_term_load($destination_id);


}
function destination_view($destination){
  return 'You need to activate the page manager';
}


