<?php 
/**
 * @author NMO
 *
 * check : http://ygerasimov.com/ctools-plugins-system
 *
 */
module_load_include ( 'php', 'dpisocial', 'dpisocial.api' );

function dpisocial_menu() {
  $items = array();
  
  $items['admin/config/dpisocial/networks'] = array (
    'title' => 'Configure social shares on comments',
    'description' => 'Select on which social networks comments can be shared.',
    'page callback' => 'dpisocial_listplugin',
    'access callback' => TRUE,
	'page arguments' => array(4),
    'access arguments' => array (
      'administer dpisocial' 
    ), 
  );
  
  return $items;
 
}

/**
 * Implements hook_ctools_plugin_type().
 *
 * Has plenty options. See ctools/help/plugins-creating.html
 */
function dpisocial_ctools_plugin_type() {
  return array(
    'social_network' => array(
      'use hooks' => TRUE,
    ),
  );
}

function dpisocial_ctools_plugin_directory($module, $plugin) {
  if (($module == 'dpisocial') && ($plugin == 'social_network')) {
    return 'plugins';
  }
}

function dpisocial_adminplugin($network) {
	return $network;
}

function dpisocial_listplugin($network) {
  $output = '';
  ctools_include('plugins');
  $social_network = ctools_get_plugins('dpisocial', 'social_network');
  
  if ($network) {
	  
	  $class = false;
	  
	  foreach ($social_network as $snetwork) {
		  if ($snetwork['type']==$network) $class=$snetwork['handler']['class'];
	  }

	  if ($class) {
		
		$form_state['class'] = $class;
		  
		$form = drupal_get_form('social_network_settings_form',$form_state);
		
		$output = drupal_render($form);  
	  } else {
		$output = 'Plugin Not Found';  
	  }
  } else {
	  foreach ($social_network as $snetwork) {
		  $output.='<a href="./'.$snetwork['type'].'">'.$snetwork['label'].'</a><br />';
	  }
	   dpm(dpisocial_getListActions());
  }
  
  return $output;	
}

function dpisocial_getListActions() {
	$actions = array(
		'share_comment'
	);	
	
	drupal_alter('dpisocial_list_actions', $actions);
	
	return $actions;	
}

function social_network_settings_form($form, &$form_state) {
	
	$class = $form_state['build_info']['args'][0]['class'];
	
	$nclass = new $class;
	
	$form['social_network_in_use']= array(
		'#title' => t('Utiliser ce réseau sur le site'),
		'#type' => 'checkbox',
		'#default_value'=>$nclass->isNetworkInUse()
	);
	
	$form += $nclass->configForm();
	
	return $form;
}

function social_network_settings_form_submit($form, &$form_state) {
	
	$class = $form_state['build_info']['args'][0]['class'];
	
	$nclass = new $class;
	
	//sauvegarde l'activation du réseau
	$nclass->setNetworkInUse($form_state['values']['social_network_in_use']);
	
	$nclass->saveConfigForm($form_state);
	
}

/**
 * Implementation of hook_permission
 *
 * @return multitype:array
 */
function dpisocial_permission() {
  return array (
    'administer dpisocial' => array (
      'title' => t ( 'Administer dpisocial' ),
      'description' => t ( 'Perform administration tasks for dpisocial module.' ) 
    ) 
  );
}

function dpisocial_page_alter(&$page) {
  ctools_include('plugins');
  $social_network = ctools_get_plugins('dpisocial', 'social_network');
  
  foreach ($social_network as $snetwork) {
	 $class = $snetwork['handler']['class'];
	 $nclass = new $class();
	 
	 if ($nclass->isNetworkInUse()) {
		 $html = $nclass->getSocialHTML();
		  
		 if ($html!=NULL) {
			$page['content']['dpisocial'][$nclass->whoAmI] = $html;	 
		 }
		 
		 $js = $nclass->getSocialJS();
		 
		 if ($js!=NULL) {
			foreach($js as $s) {
				drupal_add_js($s['script'],array('type'=>$s['type'], 'scope'=>$s['scope']));
			}
		 }
	 }
  }
}

function dpisocial_form_comment_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'dpisocial_form_comment_form_submit';	
	
  ctools_include('plugins');
  $social_network = ctools_get_plugins('dpisocial', 'social_network');
  
  foreach ($social_network as $snetwork) {
	  $class = $snetwork['handler']['class'];
	  $nclass = new $class();
	  
	  if (($nclass->isNetworkInUse()) && ($nclass->isActionActivated('share_comment'))) {
		  $nclass->addCheckboxShareComment($form);
	  }
	 
  } 	
}

/*
function dpisocial_form_alter(&$form, &$form_state, $form_id) {
  ctools_include('plugins');
  $social_network = ctools_get_plugins('dpisocial', 'social_network');
  
  foreach ($social_network as $snetwork) {
	  $class = $snetwork['handler']['class'];
	  $nclass = new $class();
	  
	  if ($nclass->isActionActivated('share_comment')) {
		  $nclass->addCheckboxShareComment($form);
	  }
	 
  }    
}
*/

function dpisocial_form_comment_form_submit(&$form, &$form_state, $form_id) {
	// check de dpisocial_facebook_share_comment
	if ($form_state['values']['dpisocial_facebook_share_comment']==1) {
		if ($form_state['redirect']==NULL) {
			$url = current_path();
			$query['share_comment']=1;
			$form_state['redirect'] = array($url, array('query'=>$query));
		} else {
			if (empty($form_state['redirect'][1]['query'])) $form_state['redirect'][1]['query'] = array('share_comment'=>1);
			else $form_state['redirect'][1]['query']['share_comment']=1;
		}
	}
}

function dpisocial_field_extra_fields() {

  $extrafield_name = 'dpisocial_share';

  foreach (array('page', 'article','package') as $node_type) {

    $extra['node'][$node_type]['display'][$extrafield_name] = array(

      'label' => t('DPI Social Boutons de partage'),

      'description' => t('Les boutons de partage sur les différents réseaux sociaux.'),

      'weight' => 50, // default weight, can be changed on display form by site-builder.

    );

  }

  return $extra;

 }
 
 function dpisocial_node_view($node, $view_mode, $langcode) {

  $extrafields = field_extra_fields_get_display('node', $node->type, $view_mode);

  $extrafield_name = 'dpisocial_share';

  if (isset($extrafields[$extrafield_name])

      && isset($extrafields[$extrafield_name]['visible'])

      && $extrafields[$extrafield_name]['visible']) {

    // Your logic here.

    $node->content[$extrafield_name] = array('#markup' => "<div class='fb-share-button' data-layout='button_count'></div><a href='https://twitter.com/share' class='twitter-share-button' data-lang='fr'>Tweeter</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>");

  }

}