<?php 
module_load_include('inc', 'dpicache','dpicache.api');
module_load_include('inc', 'dpicache','dpicache.private');


function dpicache_cron(){
  //We need to ensure everybody is sync
  $time=time();
  dpicache_regenerate_cache_entries($time);
  dpicache_cron_cleanup($time);
}


function hook_dpicache_cache_entry_register(){
  return array(
    'flowmix_render'=>array(
      'callback'=> 'flowmix_get_render', // function to call
      'plugin'=> 'dpicache_memcache', // which storage?
      'catagory'=> 'flowmix_render', // group
      'data_type' => "string", // the callback returns a string
      'ttl' => 7*24*60*60, //(in seconds) keep a cache for one week 
      'refresh_interval'=> 5*60 //(in seconds) auto-refresh cache every 5 minutes
    )
  );
}



function dpicache_dpilog_register(){

  return array(
    "dpicache"=>array(
      "actions"=>array("cache_hit","cache_miss",'regenerate_hot','regenerate_cold','error'),
    )
  );
}