<?php

/**
 * Implementation of hook_menu
 */
function dpinewssitemap_menu() {
  $items = array();

  $items[DPI_ADMIN_PATH.'/dpisitemap/newssitemap'] = array(
    'title'            => t('News Sitemap'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpinewssitemap_admin_settings_page_form'),
    'access arguments' => array('administer sitemaps'),
    'file'             => 'includes/dpinewssitemap.pages.admin.inc',
    'weight'           => 1,
    'type'             => MENU_LOCAL_TASK,
  );

  return $items;
}
