<?php

module_load_include('inc', 'cciadmin', 'cciadmin.api');
module_load_include('inc', 'cciadmin', 'cciadmin.private');

/**
 * Implementation of the hook_module
 */
function ccimapping_menu() {
  $items = array();

  $cci_path_size = sizeof(explode('/', CCI_ADMIN_PATH));

  $items[CCI_ADMIN_PATH.'/ccimapping/configuration'] = array(
    'title' => t('CCI Newsgate - Mapping configuration & settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_form_configuration_form'),
    'access arguments' => array('administer cci'),
    'file' => 'includes/ccimapping.admin.inc',
  );

  $items[CCI_ADMIN_PATH.'/ccimapping/packagetype/editor'] = array(
    'title' => t('Packagetype Editor'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_form_packagetype_editor_form', $cci_path_size + 3),
    'access arguments' => array('administer cci'),
    'file' => 'includes/packagetype.editor.inc',
  );

  $items[CCI_ADMIN_PATH.'/ccimapping/productinfo/editor'] = array(
    'title' => t('Product Info editor'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_form_productinfo_editor_form', $cci_path_size + 3),
    'access arguments' => array('administer cci'),
    'file' => 'includes/productinfo.editor.inc',
  );
  
  $items[CCI_ADMIN_PATH.'/ccimapping/cropsync'] = array(
    'title' => t('Cropings Synchronisation'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_cropsync_form_cropings_editor_form'),
    'access arguments' => array('administer cci'),
    'file' => 'includes/ccimapping.cropsync.inc',
  );

  return $items;
}

/**
 * Implementation of the hook_theme
 */
function ccimapping_theme() {
  $path = drupal_get_path('module', 'ccimapping');
  $base = array(
    'file' => 'theme.inc',
    'path' => $path.'/templates',
  );
  return array(
    'ccimapping_typeselector' => $base + array(
      'variables' => array('type' => ''),
      'template' => 'ccimapping-typeselector',
    ),
  );
}

// @todo : Adapt this to DPI7
/*
function ccimapping_wimprt_object_after_process_alter(&$node) {
  if ($node->type == 'wally_textobject') {
    $array_node = (array)$node;
    foreach ($array_node as $field_name => $field) {
      if (is_array($field) && is_array($field[0]) && isset($field[0]['format'])) {
        $node->{$field_name}[0]['value'] = _ccimapping_convert_marker_to_tags($field[0]['value']);
      }
    }
  }
  
  return;
}
*/
