<?php
/**
 * @author GVD - LBA
 */
module_load_include ( 'php', 'dpicontext', 'dpicontext.api' );

/**
 * Implementation of hook_menu
 *
 * @return multitype:array
 */
function dpicontext_menu() {
  $items = array();
  
  $items ['admin/config/dpicontext'] = array (
    'title' => 'Create customs dpicontext',
    'description' => 'Allow admin to create specific dpicontext.',
    'position' => 'right',
    'weight' => - 5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array (
      'administer dpicontext' 
    ),
    'file' => 'system.admin.inc',
    'file_path' => drupal_get_path ( 'module', 'system' ) 
  );
  
  $items ['admin/config/dpicontext/settings'] = array (
    'title' => 'Customs contexts settings',
    'description' => 'Modify context\'s propreties.',
    'page callback' => 'dpicontext_view_page',
    'access callback' => TRUE,
    'access arguments' => array (
      'administer dpicontext' 
    ),
    'file' => 'dpicontext.pages.view.inc',
    'file path' => drupal_get_path ( 'module', 'dpicontext' ) . '/includes' 
  );
  
  $items ['admin/config/dpicontext/settings/settings'] = array (
    'title' => 'Settings',
    'description' => 'Set contexts options',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array (
      'dpicontext_settings_form' 
    ),
    'access arguments' => array (
      'administer dpicontext' 
    ),
    'file' => 'dpicontext.pages.admin.inc',
    'file path' => drupal_get_path ( 'module', 'dpicontext' ) . '/includes' 
  );
  
  $items ['admin/config/dpicontext/settings/view'] = array (
    'title' => 'List',
    'description' => 'View contexts',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    "weight" => - 40 
  );
  
  $items ['admin/config/dpicontext/settings/add'] = array (
    'title' => 'Add customs contexts settings',
    'description' => 'Add context\'s propreties.',
    'page callback' => 'dpicontext_add_or_edit',
    'access arguments' => array (
      'administer dpicontext' 
    ),
    'file' => 'dpicontext.pages.add_or_edit.inc',
    'file path' => drupal_get_path ( 'module', 'dpicontext' ) . '/includes' 
  );
  
  $items ['admin/config/dpicontext/settings/edit/%'] = array (
    'title' => 'Add customs contexts settings',
    'description' => 'Add context\'s propreties.',
    'page callback' => 'dpicontext_add_or_edit',
    'page arguments' => array (
      5 
    ),
    'access arguments' => array (
      'administer dpicontext' 
    ),
    'file' => 'dpicontext.pages.add_or_edit.inc',
    'file path' => drupal_get_path ( 'module', 'dpicontext' ) . '/includes' 
  );
  
  $items ['admin/config/dpicontext/settings/delete/%'] = array (
    'title' => 'Add customs contexts settings',
    'description' => 'Add context\'s propreties.',
    'page callback' => 'dpicontext_delete',
    'page arguments' => array (
      5 
    ),
    'access arguments' => array (
      'administer dpicontext' 
    ),
    'file' => 'dpicontext.pages.delete.inc',
    'file path' => drupal_get_path ( 'module', 'dpicontext' ) . '/includes' 
  );
  
  return $items;
}

/**
 * Implementation of hook_permission
 *
 * @return multitype:array
 */
function dpicontext_permission() {
  return array (
    'administer dpicontext' => array (
      'title' => t ( 'Administer dpicontext' ),
      'description' => t ( 'Perform administration tasks for dpicontext module.' ) 
    ) 
  );
}

/**
 * Implementation of hook_ctools_plugin_directory
 *
 * @param String $owner          
 * @param String $plugin_type          
 * @return string
 */
function dpicontext_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'access') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implementation of hook_theme
 * Use: create table form element
 *
 * @return multitype:array
 */
function dpicontext_theme($existing, $type, $theme, $path) {
  return array (
    'dpicontext_table_theme' => array (
      'render element' => 'element',
      'file' => 'includes/dpicontext.pages.admin.inc' 
    ) 
  );
}
