<?php
module_load_include ( 'inc', 'dpissologinmanagerserver', 'dpissologinmanagerserver.api' );

/**
 * Implementation of hook_menu()
 */
function dpissologinmanagerserver_menu() {
  $items = array ();
  
  $items ['getLoginIdForAccessToken'] = array (
    'title' => t ( 'getLoginIdForAccessToken' ),
    'page callback' => 'dpissologinmanager_get_loginid_for_access_token',
    'access arguments' => array (
      'administer dpisso' 
    ),
    'description' => t ( 'Manage SSO&Paywall settings' ),
    'file' => 'includes/dpisso.pages.loginmanager.admin.inc' 
  );
  
  $items [DPI_ADMIN_PATH . '/dpissologinmanagerserver'] = array (
    'title' => t ( 'DpiSSO: Login Manager Server' ),
    'page callback' => 'drupal_get_form',
    'page arguments' => array (
      'dpissologinmanagerserver_manage_account_form' 
    ),
    'access arguments' => array (
      'administer dpissologinmanagerserver' 
    ),
    'description' => t ( 'Manage login manager server' ) 
  // 'file path' => drupal_get_path('module', 'dpisso').'/includes/dpisso_loginmanager_account_settings_form.inc',
    );
  
  return $items;
}

function dpissologinmanagerserver_block_info() {
  $blocks ['sso_login_form'] = array (
    'info' => t ( 'SSO login form' ),
    'cache' => DRUPAL_NO_CACHE 
  );
  return $blocks;
}

function dpissologinmanagerserver_block_view($delta = '') {
  $block = array (
    'subject' => t ( 'Dpisso login form connexion' ),
    'content' => drupal_get_form('dpissologinmanagerserver_login_access_form'),
  );
  return $block;
}

function dpissologinmanager_get_loginid_for_access_token() {
}

function dpissologinmanagerserver_manage_account_form() {
  $form = array ();
  
  $form ["new_sso_user"] = array (
    '#type' => 'fieldset',
    '#title' => 'Create a new user' 
  );
  
  $form ["new_sso_user"] ['mail'] = array (
    '#type' => 'textfield',
    '#title' => 'Email Adress' 
  );
  $form ["new_sso_user"] ['password'] = array (
    '#type' => 'textfield',
    '#title' => 'Password' 
  );
  $form ["new_sso_user"] ['loginid'] = array (
    '#type' => 'value',
    '#value' => uniqid ( 'login_id' ) 
  );
  $form ["new_sso_user"] ['submit'] = array (
    '#type' => 'submit',
    '#value' => 'Add user' 
  );
  
  $form ['sso_list'] = array (
    '#markup' => 'Tableau HTML' 
  );
  
  return $form;
}

function dpissologinmanagerserver_manage_account_form_validate($form, $form_state) {
  if (dpissologinmanagerserver_api_check_email_unicity ( $form_state ['values'] ['mail'] ) !== TRUE) {
    form_set_error ( 'mail', "Email already exist" );
  }
  if ($dpisso_unicity = dpissologinmanagerserver_api_check_loginid_unicity ( $form_state ['values'] ['loginid'] ) !== TRUE) {
    form_set_error ( 'loginid', 'Id is already use' );
  }
}

function dpissologinmanagerserver_manage_account_form_submit($form, $form_state) {
  require_once DRUPAL_ROOT . '/' . variable_get ( 'password_inc', 'includes/password.inc' );
  $values = $form_state ['values'];
  $sso_user ['mail'] = $values ['mail'];
  $sso_user ['pass'] = user_hash_password ( $values ['password'] );
  $sso_user ['loginId'] = $values ['loginid'];
  if (drupal_write_record ( 'dpissologinmanager_users', $sso_user ) != FALSE) {
    drupal_set_message ( 'Records success' );
  } else {
    drupal_set_message ( 'There was a problem !', 'error' );
  }
}

function dpissologinmanagerserver_login_access_form(){
  $form = array();
  
  $form ["new_sso_login"] = array (
    '#type' => 'fieldset',
  );
  
  $form ["new_sso_login"] ['mail'] = array (
    '#type' => 'textfield',
    '#title' => 'Email Adress'
  );
  
  $form ["new_sso_login"] ['password'] = array (
    '#type' => 'password',
    '#title' => 'Password',
  );
  
  $form ["new_sso_login"] ['submit'] = array (
    '#type' => 'submit',
    '#value' => 'Connexion'
  );
  
  return $form;
}

function dpissologinmanagerserver_login_access_form_validate($form, $form_state){
  if(!isset($form_state['values']['mail']) || $form_state['values']['mail']==""){
    form_set_error('mail', 'Enter mail please !');
  }
  if(!isset($form_state['values']['password']) || $form_state['values']['password']==""){
    form_set_error('password', 'Enter a password please !');
  }
}

function dpissologinmanagerserver_login_access_form_submit($form, $form_state){
  if(($user = dpissologinmanagerserver_api_validate_connexion($form_state['values']['mail'], $form_state['values']['password']))!=FALSE){
    //redirect
    dsm($user);
    drupal_set_message('connexion success');
  }else{
    drupal_set_message('mail or password is not correct', 'error');
  }
}