<?php 

module_load_include('inc', 'dpissologinmanagerserver','dpissologinmanagerserver.api');


/**
 * Implementation of hook_menu()
 */
function dpissologinmanagerserver_menu() {
  $items = array();

  $items['getLoginIdForAccessToken'] = array(
    'title'            => t('getLoginIdForAccessToken'),
    'page callback'    => 'dpissologinmanager_get_loginid_for_access_token',
    'access arguments' => array('administer dpisso'),
    'description'      => t('Manage SSO&Paywall settings'),
    'file'             => 'includes/dpisso.pages.loginmanager.admin.inc',
  );

  $items[DPI_ADMIN_PATH.'/dpissologinmanagerserver'] = array(
    'title'            => t('DpiSSO: Login Manager Server'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpissologinmanagerserver_manage_account_form'),
    'access arguments' => array('administer dpissologinmanagerserver'),
    'description'      => t('Manage login manager server'),
    //    'file path' => drupal_get_path('module', 'dpisso').'/includes',
  );


  return $items;
}


function dpissologinmanager_get_loginid_for_access_token(){


}

function dpissologinmanagerserver_manage_account_form(){
  $form=array();

  $form["new_sso_user"]=array(
    '#type'=>'fieldset',
    '#title'=>'Create a new user'
  );

  $form["new_sso_user"]['mail']=array(
    '#type'=>'textfield',
    '#title'=>'Email Adress'
  );
  $form["new_sso_user"]['password']=array(
    '#type'=>'textfield',
    '#title'=>'Password'
  );
  $form["new_sso_user"]['loginid']=array(
    '#type'=>'value',
    '#value'=>uniqid('login_id')
  );
  $form["new_sso_user"]['submit']=array(
    '#type'=>'submit',
    '#value'=>'Add user'
  );



  $form['sso_list']=array(
    '#markup'=>'Tableau HTML',
  );




  return $form;
}

function dpissologinmanagerserver_manage_account_form_validate($form,$form_state){
  dsm($form_state);

  if(dpissologinmanagerserver_api_check_email_unicity()!==TRUE){
    form_set_error("Email already exist");
  }
  if($dpisso_unicity=dpissologinmanagerserver_api_check_loginid_unicity()!==TRUE){
    form_set_error("idSSO not unique please try again");
  }

}


function dpissologinmanagerserver_manage_account_form_submit($form,$form_state){

  $values=$form_state['values'];

  $sso_user['mail']=$values['mail'];
  $sso_user['pass']=$values['password'];
  $sso_user['loginId']=$values['loginid'];
  dsm($sso_user);
  drupal_write_record('dpissologinmanager_users', $sso_user);
  
}


/*
 *
require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
$edit['pass'] = user_hash_password(trim($edit['pass']));


*
*/