<?php
module_load_include('inc', 'dpicontenttypes','dpicontenttypes.api');
module_load_include('inc', 'dpicontenttypes','dpicontenttypes.fields');
module_load_include('inc', 'dpicontenttypes','dpicontenttypes.entity');
module_load_include('inc', 'dpicontenttypes','dpicontenttypes.private');
include_once 'dpicontenttypes.features.inc';



/**
* Implementation of hook_menu()
*/
function dpicontenttypes_menu(){
  $items = array();
  
  $dpiproperties_uri = 'dpiproperties/%dpiproperties';
  $dpiproperties_uri_argument_position = 1;
  
  $items[$dpiproperties_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('dpiproperties', $dpiproperties_uri_argument_position),
    'page callback' => 'dpiproperties_view',
    'page arguments' => array($dpiproperties_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'dpiproperties', $dpiproperties_uri_argument_position),
    'file' => 'dpicontenttypes.entity.inc',
  );
  
  $items[$dpiproperties_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  
  $items[$dpiproperties_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpiproperties_form', $dpiproperties_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'dpiproperties', $dpiproperties_uri_argument_position),
    'file' => 'dpicontenttypes.entity.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  
  $items['admin/structure/dpiproperties-types/%dpiproperties_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpiproperties_type_form_delete_confirm', 4),
    'access arguments' => array('administer dpiproperties types'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'dpicontenttypes.entity.inc',
  );
  
  return $items;
}

/**
* Implementation of hook_permission()
*/
function dpicontenttypes_permission(){
  return array(
    'administer dpiproperties' =>  array(
      'title' => t('Administer DPI properties'),
      'restrict access' => TRUE,
    ),
    'view dpiproperties' => array(
      'title' => t('View DPI properties'),
    ),
    'edit dpiproperties' => array(
      'title' => t('Edit DPI properties'),
    ),
    'create dpiproperties' => array(
      'title' => t('Create DPI properties'),
    ),
  );
}


/**
 * Implementation of hook_node_insert
 * @param object $node
 */
function dpicontenttypes_node_insert($node){
  if (in_array($node->type, dpicontenttypes_api_getdpicontenttypes())){
    _dpicontenttypes_entityinsertdpiproperties($node, 'node', $node->nid);
  }
}
/**
*
* Implementation of hook_delete
* @param Object $node
*/
function dpicontenttypes_node_delete($node) {
  //Delete the dpiproperties entry corresponding to the node
  _dpicontenttypes_entitydeletedpiproperties($node, 'node', $node->nid);
}


function dpicontenttypes_theme(){
  return array(
    'links_lists'=>array(
      'variables'=>array(
        'atom',
        ),
      'template' => 'links-list'
      ),
    );
}

/**
 * Implements hook_scald_atom_providers.
 * Tell Scald that we'll be providing some twitter atoms.
 */
function dpicontenttypes_scald_atom_providers() {
  return array(
    'links_list' => 'Links lists'
  );
}
function dpicontenttypes_scald_add_form(&$form, &$form_state) {
 return array();
}
function dpicontenttypes_scald_add_form_fill(&$atom, $form, $form_state) {
  dsm($atom);
}
/**
 * Implements hook_scald_prerender.
 */
function dpicontenttypes_scald_prerender($atom, $context, $options, $mode) {
  dsm($atom,$mode);
  dsm($options,$options);
  
  if ($mode == 'atom') {
    if ($context != 'sdl_library_item') {
      dsm('coou');
      // we are not in the library display view, so we need more than the title and thumbnail
      
      // Tell scald core what he should display
      $view_mode="full";
      entity_view('atom', $atom, $context);
      
      dsm($atom);
      $content=entity_view('atom', $atom, $context);
      dsm($content,content);
      $atom->rendered->player = theme('links_lists', array('path' => $path) + $attributes);
      
      dsm($content,content);
      
      //Don't show title, not needed
      $atom->rendered->title = '';
    }
  }
}

/**
 * 
 * Implementation of hook_scald_atom_insert
 * Create a dpi properties linked to the new atom
 * @param Object $atom
 */
function dpicontenttypes_scald_atom_insert($atom){
  _dpicontenttypes_entityinsertdpiproperties($atom, 'scald_atom', $atom->sid);
}
/**
 * 
 * Implementation of hook_scald_atom_delete
 * Delete the dpiproperties linked to the atom
 * @param Object $atom
 */
function dpicontenttypes_scald_atom_delete($atom){
  _dpicontenttypes_entitydeletedpiproperties($atom, 'scald_atom', $atom->sid);
}



/**
 * Implement hook_form().
 *
 * Drupal needs for us to provide a form that lets the user
 * add content. This is the form that the user will see if
 * they go to node/add/node-example.
 *
 * You can get fancy with this form, or you can just punt
 * and return the default form that node_content will provide.
 */
function package_form($node, $form_state) {
  return node_content_form($node, $form_state);
}




/**
 * Implements hook_ctools_plugin_directory().
 */
function dpicontenttypes_ctools_plugin_directory($module, $plugin) {
  if ($module == 'entityreference' && $plugin == "behavior") {
	return 'plugins/entityreference/' . $plugin;
  }
  if ($module == 'dpimport' && $plugin == 'importer') {
    return 'plugins/dpimport/' . $plugin;
  }
}



/**
 * Implements hook_library().
 */
function dpicontenttypes_library() {
  $path = drupal_get_path('module', 'dpicontenttypes');
  $libraries['library'] = array(
    'title' => 'Atom reference library',
    'website' => 'http://drupal.org/project/scald',
    'version' => '1.x',
    'js' => array(
      $path . '/js/dpiatom_reference.js' => array(),
    ),
    'css' => array(
      $path . '/css/dpiatom_reference.css' => array(),
    ),
  );

  return $libraries;
}
/**
 * 
 * Implementation of the hook_dpicontenttypes_provider
 * 
 * @param String $uri
 * @return Array $provider
 */
function dpicontenttypes_dpicontenttypes_provider($uri){
  $provider = NULL;
  
  if (scald_youtube_parse_id($uri, FALSE)){
    //Youtube
    $provider = array('name' => 'scald_youtube', 'type' => 'video');
  } elseif (scald_vimeo_parse_id($uri, FALSE)){
    //Vimeo
    $provider = array('name' => 'scald_vimeo', 'type' => 'video');
  } elseif (scald_dailymotion_parse_id($uri, FALSE)){
    //Dailymotion
    $provider = array('name' => 'scald_dailymotion', 'type' => 'video');
  }
  
  return array('dpicontenttypes' => $provider);
}
