<?php

/**
 * Implementation of hook_menu().
 */
function ccidynamicfeedback_menu() {
  $items = array();
  
  $items[CCI_ADMIN_PATH.'/dynamicfeedback'] = array(
    'title' => 'Dynamic Feedback Settings',
    'description' => 'Manage informations to display in the dynamic feedback.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccidynamicfeedback_form_admin_form'),
    'access arguments' => array('administer cci'),
    'file' => 'includes/ccidynamicfeedback.admin.inc',
  );

  $items['ccidynamicfeedback/%'] = array(
    'title' => t('Dynamic feedback'),
    'page callback' => 'ccidynamicfeedback_page_render',
    'page arguments' => array(1),
    'access callback' => 1,
    'file' => 'includes/ccidynamicfeedback.render.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hooktheme().
 */
function ccidynamicfeedback_theme() {
  $path = drupal_get_path('module', 'ccidynamicfeedback');
  $base = array(
    'file' => 'theme.inc',
    'path' => $path.'/templates',
  );
  return array(
    'ccidynamicfeedback_page_render' => $base + array(
      'variables' => array('datas' => array()),
      'template' => 'ccidynamicfeedback-page-render',
    ),
  );
}
