<?php

module_load_include('inc', 'dpidam', 'dpidam.api');
module_load_include('inc', 'dpidam', 'dpidam.private');

/**
 * Implementation of hook_menu().
 */
function dpidam_menu() {
  $items = array();

  $items['admin/dpi247/dpidam'] = array(
    'title' => t('DPI DAM Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_packages_sync_form'),
    'access arguments' => array('administer dam interactions'),
    'description' => t('Manage DAM communications settings'),
    'file' => 'includes/dpidam.pages.admin.inc',
  );

  $items['admin/dpi247/dpidam/packagessync'] = array(
    'title' => t('Packages synchronization'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_packages_sync_form'),
    'access arguments' => array('administer dam interactions'),
    'description' => t('Packages synchronization settings'),
    'file' => 'includes/dpidam.pages.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  // Sources management
  $items['admin/dpi247/dpidam/sources'] = array(
    'title' => t('Sources'),
    'page callback' => 'dpidam_page_admin_sources',
    'access arguments' => array('administer dam interactions'),
    'description' => t('Manage sources'),
    'file' => 'includes/dpidam.pages.sources.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  $items['admin/dpi247/dpidam/sources/edit/%'] = array(
    'title' => t('Edit'),
    'description' => t('Edit an existing source'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_sources_edit_source_form', 5),
    'access arguments' => array('administer dam interactions'),
    'file' => 'includes/dpidam.pages.sources.inc',
  );

  $items['admin/dpi247/dpidam/sources/delete/%'] = array(
    'title' => t('Delete'),
    'description' => t('Delete a source'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_source_delete_source_form', 5),
    'access arguments' => array('administer dam interactions'),
    'file' => 'includes/dpidam.pages.sources.inc',
  );

  // Search settings and profiles management
  $items['admin/dpi247/dpidam/search'] = array(
    'title' => t('Search'),
    'page callback' => 'dpidam_page_admin_search',
    'access arguments' => array('administer dam interactions'),
    'description' => t('Search settings'),
    'file' => 'includes/dpidam.pages.search.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  $items['admin/dpi247/dpidam/search/edit/%'] = array(
    'title' => t('Edit'),
    'description' => t('Edit an existing DAM search profile.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_search_edit_profile_form', 5),
    'access arguments' => array('administer dam interactions'),
    'file' => 'includes/dpidam.pages.search.inc',
  );

  $items['admin/dpi247/dpidam/search/delete/%'] = array(
    'title' => t('Delete'),
    'description' => t('Delete a DAM search profile.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_search_delete_profile_form', 5),
    'access arguments' => array('administer dam interactions'),
    'file' => 'includes/dpidam.pages.search.inc',
  );

  $items['admin/dpi247/dpidam/search/setdefault/%'] = array(
    'title' => t('Set as default'),
    'description' => t('Set a DAM search profile as default profile.'),
    'page callback' => 'dpidam_page_admin_search_set_default_profile',
    'page arguments' => array(5),
    'access arguments' => array('administer dam interactions'),
    'file' => 'includes/dpidam.pages.search.inc',
  );

  $items['admin/dpi247/dpidam/archive'] = array(
    'title' => t('Archive recovery'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_archive_form'),
    'access arguments' => array('administer dam interactions'),
    'description' => t('Packages recovery settings'),
    'file' => 'includes/dpidam.pages.archive.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );

  $items['admin/dpi247/dpidam/historic'] = array(
    'title' => t('History archiving'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_historic_form'),
    'access arguments' => array('administer dam interactions'),
    'description' => t('Settings about old nodes history archiving'),
    'file' => 'includes/dpidam.pages.historic.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
  );

  $items['admin/dpi247/dpidam/purge'] = array(
    'title' => t('Nodes purge'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpidam_page_admin_purge_form'),
    'access arguments' => array('administer dam interactions'),
    'description' => t('Settings about old nodes purge'),
    'file' => 'includes/dpidam.pages.purge.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );

  $items['node/%node/dam'] = array(
    'title' => t('Node as archive'),
    'page callback' => 'dpidam_archive_simulation',
    'page arguments' => array(1),
    'access arguments' => array('administer dam interactions'),
    'file' => 'includes/dpidam.pages.archive.inc',
  );

  return $items;
}

/**
 * Implementation of hook_permission()
 */
function dpidam_permission(){
  return array(
    'administer dam interactions' =>  array(
      'title' => t('Administer DAM interactions'),
      'restrict access' => TRUE,
    ),
  );
}
