<?php 

module_load_include('inc', 'dpilog','dpilog.private');


/**
 * Implementation of hook_menu
 */
function dpicommons_menu(){
  $items = array();
 
  $items['admin/config/dpi247'] = array(
    'title' => 'DPI247',
    'description' => 'Parent item for DPI247',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  
  $items['admin/config/dpi247/settings'] = array(
    'title' => 'DPI247 Settings',
    'description' => 'General settings for DPI247',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dpicommons_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'dpicommons.admin.inc',
    'file path' => drupal_get_path('module', 'dpicommons').'/includes',
  );
  
  return $items;
 
}


function dpi_log($log_name, $action, $message, $severity=DPILOG_SEVERITY_DEFAULT, $uid=NULL, $id=NULL, $variables=array(), $keep_backtrace=FALSE){
  if (module_exists('dpilog')){
    _dpilog_log($log_name, $action, $message, $severity, $uid,$id,$variables,$keep_backtrace);
  }
}
/**
 * 
 * Check if an URL is valid and return a 200
 * Return TRUE if so False if not.
 * @param String $url
 * @return Boolean $response
 */
function dpicommons_checkurlresponse($url){
  $response = TRUE;
  if (!valid_url($url)){
    $response = FALSE;
  } else {
    $request = drupal_http_request($url, array('timeout' => dpi_variable_get('dpicommons_http_request_timeout', 3)));
    if ($request->code != '200'){
      $response = FALSE;
    }
  }
  return $response;
}