<?php 

module_load_include('inc', 'dpimport','dpimport.private');

/**
 * Implementation of hook_menu
 */
function dpimport_menu(){
  $items = array();

  //dpimport/process/dpixml (cas folder)
  //dpimport/process/dpixml/fichier.zip (cas fichier)
  //dpimport/process/url

  $items['dpimport/process/%'] = array(
    'title'            => t('Run XML Import'),
    'page callback'    => 'dpimport_page_process_import',
    'page arguments'   => array(2),
    'access callback'  => 'dpimport_access',
    'access arguments' => array(2),
    'file'             => 'includes/dpimport.process.inc',
    'type'             => MENU_LOCAL_TASK,
  );

  $items['admin/config/dpimport'] = array(
    'title' => 'DPImport',
    'description' => 'Parent item import',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/dpimport/import'] = array(
    'title'            => t('Import'),
    'description'      => t('Import settings'),
    'page callback'    => 'dpimport_page_importer_list',
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.pages.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
  );

  $items['admin/config/dpimport/import/list'] = array(
    'title'            => t('List'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => 0,
  );

  $items['admin/config/dpimport/import/add'] = array(
    'title'            => t('Add Import'),
    'description'      => t('Adding an import.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpimport_page_form_importer_form'),
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.pages.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 1,
  );

  $items['admin/config/dpimport/import/edit/%'] = array(
    'title'            => t('Edit Import'),
    'description'      => t('Editing an import.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpimport_page_form_importer_form', 5),
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.pages.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
    'weight'           => 1,
  );

  $items['admin/config/dpimport/import/delete/%'] = array(
    'title'            => t('Delete Import'),
    'description'      => t('Deleting an import.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpimport_page_form_importer_delete_form', 5),
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.pages.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
    'weight'           => 1,
  );

  $items['dpimport/test/%'] = array(
    'title'            => t('Test XML POST Import'),
    'page callback'    => 'dpimport_page_test',
    'page arguments'   => array(2),
    'access arguments' => array('administer dpimport'),
    'file'             => 'includes/dpimport.process.inc',
    'type'             => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_permission
 */
function dpimport_permission() {
  return array(
    'administer dpimport' => array(
      'title' => t('Administer DPI Import'),
      'description' => t('Perform administration tasks for DPI Import.'),
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_type
 */
function dpimport_ctools_plugin_type() {
  $plugins = array(
    'importer' => array(
      'use hooks' => TRUE,
    ),
  );
  return $plugins;
  
}
/**
 * A modifier, donner la main à l'importer
 */
function dpimport_access($importer_name){
  //@todo
  return TRUE;
}

/**
 * Implementation of hook_theme
 */
function dpimport_theme(){
  $theme['dpimport_log_recursif'] = array(
    'file' => 'templates/theme.inc',
    'variables' => array('children' => NULL),
  );
  
  return $theme;
}

/**
 * Implements hook_stream_wrappers().
 */
function dpimport_stream_wrappers() {
  return array(
    'importer' => array(
      'name' => t('Importer folders'),
      'class' => 'ImporterStreamWrapper',
      'description' => t('Provides read-only paths to importer folder.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implementation of hook_cron
 */
function dpimport_cron(){
  module_load_include('inc', 'dpimport', 'includes/dpimport.process');
  dpimport_deleteoldfiles();
}
