<?php 

module_load_include('inc', 'dpimport','dpimport.private');

/**
 * Implementation of hook_menu
 */
function dpimport_menu(){
  $items = array();
  
  //dpimport/process/dpixml (cas folder)
  //dpimport/process/dpixml/fichier.zip (cas fichier)
  //dpimport/process/url
  
  
  $items['dpimport/process/%'] = array(
    'title'            => t('Run XML Import'),
    'page callback'    => 'dpimport_page_process_import',
    'page arguments'   => array(2),
    'access callback'  => 'dpimport_access',
    'access arguments' => array(2),
    'file'             => 'includes/dpimport.process.inc',
    'type'             => MENU_LOCAL_TASK,
  );
  
  $items['admin/config/dpi247/import'] = array(
    'title'            => t('Import'),
    'description'      => t('Import settings'),
    'page callback'    => 'dpimport_page_importer_list',
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.page.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
  );
  
  $items['admin/config/dpi247/import/list'] = array(
    'title'            => t('List'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => 0,
  );
  
  $items['admin/config/dpi247/import/add'] = array(
    'title'            => t('Add Import'),
    'description'      => t('Adding an import.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpimport_page_form_importer_form'),
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.page.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 1,
  );
  
  $items['admin/config/dpi247/import/edit/%'] = array(
    'title'            => t('Edit Import'),
    'description'      => t('Editing an import.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpimport_page_form_importer_form', 5),
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.page.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
    'weight'           => 1,
  );
  
  $items['admin/config/dpi247/import/delete/%'] = array(
    'title'            => t('Delete Import'),
    'description'      => t('Deleting an import.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('dpimport_page_form_importer_delete_form', 5),
    'access arguments' => array('administer dpimport'),
    'file'             => 'dpimport.admin.page.inc',
    'file path'        => drupal_get_path('module', 'dpimport').'/includes',
    'weight'           => 1,
  );
  
  $items['dpimport/test/%'] = array(
    'title'            => t('Test XML POST Import'),
    'page callback'    => 'dpimport_page_test',
    'page arguments'   => array(2),
    'access arguments' => array('administer dpimport'),
    'file'             => 'includes/dpimport.process.inc',
    'type'             => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * 
 * Implementation of hook_permission
 */
function dpimport_permission() {
  return array(
    'administer dpimport' => array(
      'title' => t('Administer DPI Import'),
      'description' => t('Perform administration tasks for DPI Import.'),
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_type
 */
function dpimport_ctools_plugin_type() {
  $plugins = array(
    'importer' => array(
      'use hooks' => TRUE,
    ),
  );
  return $plugins;
  
}
/**
 * A modifier, donner la main à l'importer
 * */
function dpimport_access($importer_name){
  return TRUE;
}

